name: Cizl
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51325
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b1cea0'
    - '#2f2f53'
    - '#8a5d13'
    - '#ab3560'
    - '#ea9d1c'
  brandStrength: 0
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
