favicon: null
name: Cizl
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.374552
  brandStrength: 0.625
  lightness: 0.7903226
  brandColors:
    - '#2a304b'
    - '#346567'
    - '#000c12'
    - '#a82927'
    - '#c87d7b'
  rhythmicContrast: 0.4659498
typography_spectrum: 1
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.57914
analytics:
  twitter: null
  google: null
  facebook: null
