layout_spectrum: 0.9292073
typography_spectrum: 1
color:
  saturation: 0.7780231
  lightness: 0.4121864
  brandStrength: 0.7060932
  brandColors:
    - '#CEC4B2'
    - '#F1EADE'
    - '#5D8A79'
    - '#E88827'
  rhythmicContrast: 0.4659498
name: Cizl
